config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :memes
  get '/memes/hashtag/:name', to: 'memes#hashtags'
  get '/policy', to: redirect('https://termsfeed.com/privacy-policy/87c4adefa87fede697ab0208f845fcd9')
  get '/explore', to: 'tags#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meme.rb
# frozen_string_literal: true

class Meme < ApplicationRecord
  # Relations
  belongs_to :user
  has_and_belongs_to_many :tags
  # Validation
  validate :picture_size
  validates :picture, presence: true

  attr_accessor :hashtags

  mount_uploader :picture, PictureUploader

  before_update do
    tags.clear
    extract_tags
  end

  def self.search(phrase)
    if phrase
      where('caption LIKE ?', "%#{phrase}%").order('id DESC')
    else
      order('id DESC')
    end
  end

  def extracted_hashtags
    tags.pluck(:name).map{ |x| '#' + x }.join(' ')
  end

  def extract_tags
    hashtags.scan(/#\w+/).uniq.each do |hashtag|
      tags.find_or_create_by(name: hashtag.downcase.delete('#'))
    end
  end

  private

  def picture_size
    if picture.size > 2.megabytes
      errors.add(:picture, 'File size cannot be greater than 2MB')
    end
  end

end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_and_belongs_to_many :memes
  has_many :users, through: :memes
  validates :name, length: { minimum: 2, maximum: 22 }

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :memes
  has_many :tags, through: :memes

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] &&  session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.image = auth.info.avatar
      user.skip_confirmation!
      user.save!
    end
  end

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  rescue_from ActiveRecord::RecordNotFound, with: :back_to_memes

  def back_to_memes(exception)
    redirect_to root_path
  end
end

app/controllers/memes_controller.rb
# frozen_string_literal: true

class MemesController < ApplicationController
  before_action :set_meme, only: %i[show edit update destroy]

  def index
    @memes = current_user.memes.search(params[:phrase])
  end

  def show; end

  def new
    @meme = Meme.new
  end

  def edit; end

  def create
    respond_to do |format|
      @meme = MemeCreator.new(meme_params, current_user).call 
      if @meme.persisted? 
        format.html { redirect_to @meme, notice: 'Meme was succesfully uploaded' }
        format.json { render :show, status: :created, location: @meme }
      else
        format.html { render :new }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @meme.update(meme_params)
        format.html { redirect_to @meme, notice: 'Meme was succesfully updated' }
        format.json { render :show, status: :ok, location: @meme }
      else
        format.html { render :new }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  def hashtags
    tag = Tag.find_by(name: params[:name]) or not_found
    @hashtag = tag.name
    @memes = tag.memes.where(user_id: current_user.id)
  end

  def destroy
    @meme.destroy!
    respond_to do |format|
      format.html do
        redirect_to memes_url, notice:
                   'Meme was succesfully deleted'
      end
      format.json { head :no_content }
    end
  end

  private

  def set_meme
    @meme = current_user.memes.find(params[:id]) 
  end

  def meme_params
    params.require(:meme).permit(:caption, :picture, :user_id, :hashtags)
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  def index
    @tags = Tag.all.order(name: :asc)
    #= TagDecorator.decorate_collection(Tag.all)
  end      

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
      @user = User.from_omniauth(request.env["omniauth.auth"])
  
      if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  
    def failure
      redirect_to root_path
    end
  end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @memes = Meme.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/memes_helper.rb
# frozen_string_literal: true

module MemesHelper
  def render_with_hashtags(hashtags)
    hashtags.gsub(/#\w+/) { |tag| link_to tag, "/memes/hashtag/#{tag.downcase.delete('#')}" }.html_safe
  end
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="page-footer font-small footer">
  <div class="container"> 
    <%= link_to 'Privacy policy', policy_path %>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-static-top">
<div class="container"> 
<a class="navbar-brand" href="/memes"><i class="fa fa-folder-open"></i> MyMemeFolder</a>
  <% if current_user %>
    <ul class="nav navbar-nav">
      <li><%= link_to "Upload", new_meme_path  %></li>
      <li><%= link_to "Explore", explore_path  %></li>
    </ul>
  <% end %>
    <ul class="nav navbar-right col-md-4">
      <% if current_user %>
        <li class="col-md-8 user-name">
          <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe,
                                      edit_user_registration_path, title: 'Edit Profile'%>
        </li>
        <li class="col-md-3 logout"><%= link_to('Logout', destroy_user_session_path,
                                                class: 'btn btn-xs btn-danger', title: 'Logout', :method => :delete) %></li>
      <% else %>
        <li class="col-md-4 pull-right">
          <%= link_to('Sign In', new_user_session_path, class: 'btn btn-primary', title: 'Sign In') %>
        </li>
      <% end %>
    </ul>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MyMemeFolder" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

 <%= render '/layouts/navigation'%>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

    </div> <!-- /container -->

    <%= render '/layouts/footer'%>
    
  </body>
</html>

app/views/memes/_form.html.erb
<%= form_for @meme, html: { multipart: true, :class => "form-horizontal meme" } do |f| %>

  <% if @meme.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@meme.errors.count, "error") %> prohibited this meme from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @meme.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :caption, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :caption, :class => 'form-control' %>
    </div>
    <%=f.error_span(:caption) %>
  </div>
  <div class="form-group">
    <%= f.label :picture, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </div>
    <%= f.error_span(:picture) %>
  </div>
  <div class="form-group">
    <%= f.label :hashtags, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :hashtags, class: 'form-control', value: @meme.extracted_hashtags %>
    </div>
    <%=f.error_span(:hashtags) %>
  </div>


    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Upload meme", :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                memes_path, :class => 'btn btn-default' %>
    </div>

<% end %>


<script type="text/javascript">
  $('#meme_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 2) {
    alert('Maximum file size is 2MB.');
    }
  });
</script>

app/views/memes/_list.html.erb
<div class="row text-center">
    <% @memes.each do |meme| %>
      <div class="col-lg-3 col-md-4 col-xs-6 hor-spacing">
        <%= link_to meme_path(meme), class: 'd-block mb-4' do %>
          <%= image_tag meme.picture.url, class: 'img-fluid img-thumbnail mini', alt: 'caption' %>
        <% end %>
      </div>
    <% end %>
</div>

app/views/memes/_search.html.erb
<div class="row search-bar">
  <%= form_tag(memes_path, method: :get, id: 'meme-search') do %>
    <div class="col-md-2">
    </div>
    <div class="col-md-6">
      <%= text_field_tag :phrase, params[:phrase], class: 'form-control'  %>
    </div>
    <div class="col-md-2">
      <%= button_tag(type: :submit, class: "btn btn-default", name: nil) do %>
        <i class="fa fa-search"></i> Search
      <% end %>
    </div>
    </div>
  <% end %>
</div>

app/views/memes/edit.html.erb
<%- model_class = Meme -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/memes/hashtags.html.erb
<%- model_class = Meme -%>
<div class="page-header">
  <h1><%= '#' + @hashtag %></h1>
</div>

<%= render 'list' %>

app/views/memes/index.html.erb
<%= render 'search' %>

<%= render 'list' %>

app/views/memes/new.html.erb
<%- model_class = Meme -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/memes/show.html.erb
<%- model_class = Meme -%>
<dl class="dl-horizontal">
  <dt></dt>
  <dd> <%= image_tag @meme.picture.url, width: 500  if @meme.picture?%> </dd>
  <dt><strong><%= model_class.human_attribute_name(:caption) %>:</strong></dt>
  <dd> <%= @meme.caption %>
  <% if @meme.extracted_hashtags.present? %>
  <dt><strong><%= model_class.human_attribute_name(:hashtags) %>:</strong></dt>
  <dd><%= render_with_hashtags(@meme.extracted_hashtags) %></dd>
  <% end %>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              memes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_meme_path(@meme), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              meme_path(@meme),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/tags/index.html.erb
<div class="container">
  <% @tags.each do |tag| %>
    <div class="row">
      <%= link_to("##{tag.name}", "/memes/hashtag/#{tag.name}")  
      #tag.hashtag_link 
      %>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<% if current_user %>
  <% controller.redirect_to memes_path %>
<% else %>
  <div class="jumbotron">
    <h2>Your Online Meme Storage</h2>
    <ul class="feature-list">
      <li> Upload your memes</li>
      <li> Categorize them</li>
      <li> Reach for them from any device</li>
    </ul>
    <p id="signup-button">
      <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary btn-lg sign-up-btn' %>
    </p>
  </div>
<% end %>